### ISSUE TITLE
How can i make a seed a head?

### ISSUE THREAD

**Issue by TheWeirdCoder** [thetealviper/Spigot_FarmCraft#4]
Hey! So right now im tinkering with the default config, but i was wondering how i could make a seed a player head WITH a texture

I set the seed to a head, but the texture is not working.

if you could help, i'd appreciate it! Cheers.

```
Seed:
id: PLAYER_HEAD
headtexture: 40d532f8bdd02d88fae0fac1f9ffafde5c6c0ee28d1827a421c4b4ca331157bd
name: '&rCorn Seed'
lore:
- '&r&7Plant me in tilled dirt!'
tags: 
- unbreakable:1
flags:
- HIDE_ATTRIBUTES
- HIDE_UNBREAKABLE
```

**Comment by thetealviper** [comment]
Apologies for the semi-late response. GitHub does not give me notifications and I was sick for a while so I didn't check my email. I see that I have not adequately explained seed item creation, nor have I adequately explained normal item creation syntax since updates modernizing it with more features. For a seed which is a playerhead, I'll provide the code below and trust that you can connect the dots as to how it works. I simply have no communicated it clearly anywhere, and I apologize for that!

```
Seed:
  id: PLAYER_HEAD
  name: '&rCorn Seed'
  lore:
  - '&r&7Plant me in tilled dirt!'
  tags:
  - unbreakable:1
  - "textureskull:59970d085bf5aae875165f8337896242c12cd11299df89891a8a813adeb8"
  flags:
  - HIDE_ATTRIBUTES
  - HIDE_UNBREAKABLE
```

I anticipate not getting around to updating everything with proper documentation of the syntax, so since you reached out directly here is the full list of general customization options everywhere an "item" can be defined within the configs (minus implementation-specific nuances like harvests needing percentages and stuff like that):

```
* id: DIRT
* amount: 1
* name: "Dirt"
* lore:
*  - "Lore Line 1"
*  - "Lore Line 2"
* enchantments:
*  - "arrowdamage:1"
*  - "arrowfire:1"
*  - "arrowinfinite:1"
*  - "arrowknockback:1"
*  - "damage:1"
*  - "digspeed:1"
*  - "durability:1"
*  - "fireaspect:1"
*  - "knockback:1"
*  - "lootbonusblock:1"
*  - "lootbonusmob:1"
*  - "luck:1"
*  - "protectionfall:1"
*  - "protectionfire:1"
*  - "silktouch:1"
* tags:
*  - "textureskull:SKINVALUE"
*  - "playerskull:PLAYERNAME"
*  - "vanilladurability:256"
*  - "unbreakable:true"
*  - "custommodeldata:1234567"
*  - "fakeenchant:true" //Adds enchant glow to item without any enchantments
* flags:
*  - "HIDE_ATTRIBUTES"
*  - "HIDE_DESTROYS"
*  - "HIDE_ENCHANTS"
*  - "HIDE_PLACED_ON"
*  - "HIDE_POTION_EFFECTS"
*  - "HIDE_UNBREAKABLE"
* attributes:
*  - "ATTRIBUTE:VALUE:OPERATION"
*  - "ATTRIBUTE:VALUE:OPERATION:SLOT"
*  - ATTRIBUTE NAMES FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/Attribute.html 
*  - ATTRIBUTE OPERATIONS FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/attribute/AttributeModifier.Operation.html
*  - ATTRIBUTE SLOTS FOUND @ https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/EquipmentSlot.html
```
