### ISSUE TITLE
Requesting Plugin Support for Older Server Versions 

### ISSUE THREAD

**Issue by JTYX8X** [thetealviper/Spigot_FarmCraft#9]
I hope this plugin can support older server versions (e.g., version 1.20.6). It’s such an excellent plugin, but it’s a pity that it only supports the latest versions and cannot be used on older servers.

**Comment by thetealviper** [comment]
I swear you already sent this somewhere else and I responded to it. I can't find it anywhere to screenshot and send again here. In case I am crazy and I haven't actually responded to this question yet:

Firstly, most plugins function fine even if developed for versions ahead of what you're running. Have you TRIED running the 1.21 plugin on your 1.20.6 server? If no, do that first. Did it work?

If you tried it and it doesn't work, Spigot keeps old versions of the plugin. Go to the plugin page, and click on "Version History", and download a version closest to what you want (in this case "1.20.4.a.3" feels very close). Try running that. Did it work?

If neither a "too updated" nor "too old" version work, then you are out of luck because I don't intend on supporting every version. That is way too much work, that makes the code way too messy, and requires much more time than I'm willing to commit towards something I have no obligation to upkeep at all. If people request an update to a more recent version *because it doesn't work anymore* or report bugs, I'm still involved for maintenance, but I have no intention of feature adds or anything else towards the plugins at this time.
